first pass at getting a net developer role
searchspring/competencies pull request #107
Opened 2022-06-14 21:21 UTC by bjwest55

Not exhaustive at all but a start

2022-06-15 14:51 UTC, codeallthethingz requested changes
Awesome work!  ❤️ 

Couple of changes requested.

2022-06-15 14:51 UTC, codeallthethingz commented on roles/engineering-net-developer.md
> +Ide Rider
```suggestion
IDE Rider
```

2022-06-15 14:51 UTC, codeallthethingz commented on roles/engineering-net-developer.md
> +Prometheus
I feel like a bunch of these are common between developer and net developer and should be moved into an eng-full-stack-base role?

2022-06-15 14:51 UTC, codeallthethingz commented on competencies/azure-portal.md
> +* Poke around
I would make these more concrete things that someone could do on their own.

* ask for a tour / poke around -> spend time in the portal and read the help sections

2022-06-15 14:51 UTC, codeallthethingz commented on competencies/language-c-sharp.md
> +* Open many PRs
How many is many?   Good to put a number in.

2022-08-25 16:22 UTC, bjwest55 commented on roles/engineering-net-developer.md
> +Prometheus
Done

2022-08-25 16:48 UTC, codeallthethingz approved these changes

2022-08-25 16:48 UTC, merged