Add GitHub Actions competency
searchspring/competencies pull request #67
Opened 2020-10-08 16:52 UTC by adarj

2020-10-08 17:04 UTC, codeallthethingz requested changes
Great start!  Some additions and changes

2020-10-08 17:04 UTC, codeallthethingz commented on competencies/github-actions.md
> +* You can create a workflow that produces packages (such as NPM packages, Docker containers, etc.) and uploads them to GitHub Packages or another package hosting service.
I'd remove docker containers as we probably want to build those in some other system.

2020-10-08 17:04 UTC, codeallthethingz commented on competencies/github-actions.md
> +* You can create a continuous integration workflow for a project that automatically tests and deploys your code.
I'd remove deploys from here.  Start with just a test.

2020-10-08 17:04 UTC, codeallthethingz commented on competencies/github-actions.md
> +
Add some way to verify that they know about the different trigger mechanisms.

2020-10-08 17:04 UTC, codeallthethingz commented on competencies/github-actions.md
> +
Add something about resuing other peoples actions.

2020-10-08 17:04 UTC, codeallthethingz commented on competencies/github-actions.md
> +GitHub Actions is an API for cause and effect on GitHub: orchestrate any workflow, based on any event, while GitHub manages the execution, provides rich feedback, and secures every step along the way
are an API

2020-10-08 18:33 UTC, wafer-bw commented
@adarj - The only thing I can suggest is maybe adding a blurb about using branch protection to require github action checks to pass before a PR can be merged. I'm not sure if that's fully relevant though... your call.

2020-10-09 07:32 UTC, leukanos commented on competencies/github-actions.md
> +
Would be also good to include:
- caching `actions/cache@v2`
- conditional steps 'if: github.event.pull_request.draft == false'
- artefacts `actions/upload-artifact@v2`
- steps vs jobs

2020-10-09 18:43 UTC, adarj commented on competencies/github-actions.md
> +* You can create a continuous integration workflow for a project that automatically tests and deploys your code.
✅

2020-10-09 18:44 UTC, adarj commented on competencies/github-actions.md
> +GitHub Actions is an API for cause and effect on GitHub: orchestrate any workflow, based on any event, while GitHub manages the execution, provides rich feedback, and secures every step along the way
✅

2020-10-09 18:44 UTC, adarj commented on competencies/github-actions.md
> +* You can create a workflow that produces packages (such as NPM packages, Docker containers, etc.) and uploads them to GitHub Packages or another package hosting service.
✅

2020-10-14 19:41 UTC, adarj commented on competencies/github-actions.md
> +
✅

2020-10-14 19:43 UTC, adarj commented on competencies/github-actions.md
> +
✅

2020-10-15 15:12 UTC, codeallthethingz requested changes
see slack message for suggestions

2020-10-15 16:38 UTC, ehacke approved these changes
Looks good!

2020-10-20 15:18 UTC, codeallthethingz approved these changes
like it, merge it 🎉

2020-10-20 15:30 UTC, merged